#- hosts: all
#  gather_facts: no
#  ansible_connection: local
#  ansible_network_os: ios
#  tasks:
#  - name: configure top level configuration
#    ios_config:
#      lines: hostname {{ ROUTER_HOSTNAME }}
#    ios_command:
#        commands:
#         - "dir flash: | exclude drwx"
#    register: ios_output 
#  - debug: msg={{ios_output}}
 
- ios_command:
   commands:
    - "dir flash: | exclude drwx"
