- hosts: all
  gather_facts: no
#  ansible_connection: local
#  ansible_network_os: ios
  tasks:
#  - name: configure top level configuration
#    ios_config:
#      lines: hostname {{ ROUTER_HOSTNAME }}
#    ios_command:
#        commands:
#         - "dir flash: | exclude drwx"
#    register: ios_output 
#  - debug: msg={{ios_output}} 
   - raw: "dir flash: | exclude drwx" 
     register: ios_output

   - debug: msg="{{ios_output}}"
#   - name: run show version on remote devices
#    ios_command:
#      commands: show version

